### ISSUE TITLE
should be lifecycle :)

### ISSUE THREAD

**Issue by iamsoorena** [MacKentoch/react-redux-nextjs-bootstrap-pwa-starter#1]
https://github.com/MacKentoch/react-redux-nextjs-bootstrap-pwa-starter/blob/7aa27f9509eb83c89e7c35f3375504a9bd87f630/pages/login.js#L58

**Comment by MacKentoch** [comment]
:smile: clearly that is what is was supposed to be

**Comment by MacKentoch** [comment]
fixed
