### ISSUE TITLE
 getting an error of setClientState not defined.

### ISSUE THREAD

**Issue by ShintaroNippon** [MacKentoch/react-redux-nextjs-bootstrap-pwa-starter#2]
HI there... First of all thank by the plugin.
I'm trying to implement this feature in Next js

And I have this code...
_app.js

import { Provider } from "react-redux";
 import { appWithTranslation } from "../../i18n";
 import withRedux from "next-redux-wrapper";
 import { makeStore } from "../lib/redux";
import { PersistGate } from "redux-persist/integration/react";
export default withRedux(makeStore, { debug: true })(appWithTranslation(MyApp))
and in page/index.js I have

  export default connect(
      (state) => state,
      {setClientState}
  )(({fromClient, setClientState}))(withNamespaces('landing')(Index))

but IM getting an error of setClientState not defined.

Can you help me, please?

Thanks in advance
Carlos Vieira

**Comment by MacKentoch** [comment]
Hi @ShintaroNippon 

It is due to your connect not being well defined (talking about functions: `mapStateToProps ` and `mapDispatchToProps `).

You must define functions like these in your connect:

```javascript

// return properties of the state to set as props of your Component:
const mapStateToProps = (state) => {
  return {
    aProps: state.aProps
  };
};

// return actions (redux action are dispatched!) to set as props of your Component:
const mapDispatchToProps = dispatch => {
  return {
    setClientState: () => {
      dispatch(setClientState())
    }
  };
};

connect(mapStateToProps, mapDispatchToProps)(Component);
```

**Comment by MacKentoch** [comment]
Closing because not a real issues of the repository.

But feel free to keep messaging in 😉.
