### ISSUE TITLE
Woefully outdated

### ISSUE THREAD

**Issue by mikepc** [MacKentoch/react-redux-nextjs-bootstrap-pwa-starter#3]
This boilerplate is woefully outdated, I was really hopeful in finding it but then discovered the material UI, react and other versions were very old (by years).

Any chance you have a modern version of this lying around?

**Comment by MacKentoch** [comment]
Hi @mikepc ,

I have couple of boilerplates. 
But what do you need exactly (like bootstrap or material UI, Next JS or just SPA or home made SSR etc...).

But if you plan to start React I recommend create-react-app cli (equivalent to angular cli if you want).
